CourseManager/Presentation/Controllers/UploadsController.cs
using System;
using System.Threading.Tasks;
using Business.ServicesInterfaces;
using Business.ServicesInterfaces.Models.UploadsViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Presentation.Controllers
{
    public class UploadsController : Controller
    {
        private readonly IUploadService _service;

        public UploadsController(IUploadService service)
        {
            _service = service;
        }
        // GET: Uploads
        public IActionResult Index()
        {
            //IIdentity LoggedInUser = User.Identity;
            return View();
        }

// GET: Uploads/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: Uploads/Create
        public IActionResult Create(Guid userId)
        {
            return View();
        }

        // POST: Uploads/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string userGroup, string userFirstName, string userLastName, [Bind("Type, Week, Teacher, File")] UploadsCreateModel uploadCreateModel)
        {
            await _service.CreateUploads(userGroup, userFirstName, userLastName, uploadCreateModel);

            return RedirectToAction(nameof(Index));           
        }

        // GET: Uploads/Edit/5
        public IActionResult Edit(int id)
        {
            return View();
        }

        // POST: Uploads/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Uploads/Delete/5
        public IActionResult Delete(Guid? id)
        {
            return View();
        }

        // POST: Uploads/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Guid id)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Download(string seminarName, string group, string week, string fileName, string teacher)
        {
            {
                var file = _service.DownloadFile(seminarName, group, week, fileName, teacher);

                return File(file, "application/octet-stream", fileName);
            }
        }

    }
}

CourseManager/Presentation/Views/Uploads/Create.cshtml
@model Business.ServicesInterfaces.Models.UploadsViewModels.UploadsCreateModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Create";
}

<environment include="Development">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</environment>

<h2>Submit</h2>

<h4>Homework</h4>
<hr />
<div class="row">
    <div class="col-md-4">
    @{
        var currentUser = UserManager.Users.SingleOrDefault(user => user.Id == UserManager.GetUserId(User));
        var listTeachers = new List<SelectListItem>();
        var listWeek = new List<SelectListItem>();
        var listTypes= new List<SelectListItem>()
        {
            new SelectListItem { Text = "Laboratory", Value = "Laboratory" },
            new SelectListItem { Text = "Kata", Value = "Kata", Selected = true }
        };

        foreach (var user in UserManager.GetUsersInRoleAsync("Assistant").Result)
        {
            listTeachers.Add(new SelectListItem
            {
                Text = @user.FirstName + " " + @user.LastName,
                Value = @user.FirstName + @user.LastName
            });
        }

        foreach (var user in UserManager.GetUsersInRoleAsync("Owner").Result)
        {
            listTeachers.Add(new SelectListItem
            {
                Text = @user.FirstName + " " + @user.LastName,
                Value = @user.FirstName + @user.LastName
            });
        }

        for (var index = 1; index <= 7; ++index)
        {
            listWeek.Add(new SelectListItem
            {
                Text = "Week " + index.ToString(),
                Value = index.ToString()
            });
        }


        using (Html.BeginForm("Create", "Uploads", new { userGroup = currentUser.Group, userFirstName = currentUser.FirstName, userLastName = currentUser.LastName }, FormMethod.Post, null, new { enctype = "multipart/form-data" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <br />
                @Html.DropDownListFor(model => model.Type, listTypes, new { @class = "btn btn-default" })
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Week" class="control-label"></label>
                <br />
                @Html.DropDownListFor(model => model.Week, listWeek, new { @class = "btn btn-default" })
                <span asp-validation-for="Week" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Teacher" class="control-label"></label>
                <br />
                @Html.DropDownListFor(model => model.Teacher, listTeachers, new { @class = "btn btn-default" })
                <span asp-validation-for="Teacher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input enctype="multipart/form-data" type="file" multiple="multiple" asp-for="File" class="form-control" />
            </div>  
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
            }
        <span class="text-danger"><strong>Reminder: </strong>Only archives are allowed to upload!</span>
    }
</div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
}

CourseManager/Presentation/Views/Uploads/Delete.cshtml
@using Business.ServicesInterfaces
@inject IUploadService Service
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Delete";
}

<environment include="Development">
    <link href="~/css/Katas.css" rel="stylesheet" />
</environment>


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kata</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size: 18px;">
            Uploaded Files
        </dt>
        <dd style="font-size: 16px;">
            @{
                var currentUser = UserManager.Users.SingleOrDefault(user => user.Id == UserManager.GetUserId(User));
                foreach (var file in Service.GetFiles("Seminar", currentUser.Group, "1", currentUser.FirstName + "" + currentUser.LastName))
                {
                    @file
                    <br/>
                }
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="@UserManager.GetUserId(User)" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a class="btn btn-default" asp-action="Index">Back to List</a>
    </form>
</div>

CourseManager/Presentation/Views/Uploads/Details.cshtml
@model Kata

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kata</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size: 18px;">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd style="font-size: 16px;">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt style="font-size: 18px;">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd style="font-size: 16px;">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt style="font-size: 18px;">
            UploadedFiles
        </dt>
        <dd style="font-size: 16px;">
            @foreach (var file in Model.GetFiles())
            {
                @file
                <br />
            }
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-default" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

CourseManager/Presentation/Views/Uploads/Edit.cshtml
@model Business.ServicesInterfaces.Models.KataViewModels.KataEditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Modify the kata</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form runat="server" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="ckeditor"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span><b>Current Files:</b></span>
                <br />
                @foreach (var file in Model.GetFiles())
                {
                    @file
                    <br />
                }
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input type="file" multiple="multiple" asp-for="File" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
}

CourseManager/Presentation/Views/Uploads/Index.cshtml
@using Business.ServicesInterfaces
@model Business.ServicesInterfaces.Models.UploadsViewModels.UploadsEditModel
@inject IUploadService Service
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Uploads";
}

<environment include="Development">
    <link href="~/css/Katas.css" rel="stylesheet" />
</environment>

<h2>Uploads</h2>

<p>
    <a class="btn btn-default" asp-action="Create" asp-route-id="@UserManager.GetUserId(User)">Upload a Homework or Kata file</a>
</p>
<table class="table uploadtable">
    <thead>
    <tr>
        @if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
        {
            <th style="font-size: 22px;">
                <p align="left"><b>Type</b></p>
            </th>

            <th style="font-size: 22px;">
                <p align="left"><b>Week</b></p>
            </th>
            <th style="font-size: 22px;">
                <p align="left"><b>Content</b></p>
            </th>
        }
        else
        {
            <th style="font-size: 22px;">
                <p align="left"><b>Type</b></p>
            </th>
            <th style="font-size: 22px;">
                <p align="left"><b>Content Uploaded</b></p>
            </th>
        }
    </tr>
    </thead>
    <tbody>
        <tr>
            @{
                if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                {
                    <td>
                        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#kata">Kata</button>
                    </td>

                    var user = UserManager.GetUserAsync(User).Result;
                    var currentUser = user.FirstName + user.LastName;
                    var kataList = new List<Guid>();

                    <td style="font-size: 16px;">
                        <div id="kata" class="collapse">
                            <ul style="list-style-type: none;">
                                @for (var index = 1; index <= 7; ++index)
                                {
                                    var value = Guid.NewGuid();
                                    kataList.Add(value);

                                    <li><button type="button" class="btn btn-info" data-toggle="collapse" data-target="#@value">Kata nr. @index</button></li>
                                }
                            </ul>
                        </div>
                    </td>
                    <td>
                        @{
                            for (var index = 0; index < kataList.Count; ++index)
                            {
                                <div id="@kataList[index]" class="collapse">
                                    @foreach (var file in Service.GetAllFiles("Kata", (index + 1).ToString(), currentUser))
                                    {
                                        using (Html.BeginForm("Download", "Uploads", new { seminarName = "Kata", week = (index + 1).ToString(), fileName = @file, teacher = @currentUser }, FormMethod.Post, null, new { }))
                                        {
                                            <button class="btn btn-default">@file</button>
                                        }
                                    }
                                </div>
                            }
                        }
                    </td>

                }
                else
                {
                    var currentUser = UserManager.Users.SingleOrDefault(user => user.Id == UserManager.GetUserId(User));
                    var teachers = new List<string>();
                    var userFound = currentUser.FirstName + "" + currentUser.LastName + "" + currentUser.Group;

                    foreach (var user in UserManager.GetUsersInRoleAsync("Assistant").Result)
                    {
                        teachers.Add(@user.FirstName + @user.LastName);
                    }

                    <td style="font-size: 16px;">Kata</td>
                    <td style="font-size: 16px;">
                        @foreach (var teacher in teachers)
                        {
                            for (var index = 1; index <= 7; ++index)
                            {
                                foreach (var file in Service.GetFiles("Kata", index.ToString(), userFound, teacher))
                                {
                                    using (Html.BeginForm("Download", "Uploads", new { seminarName = "Kata", week = index.ToString(), fileName = @file, teacher = @teacher }, FormMethod.Post, null, new { }))
                                    {
                                        <button class="btn btn-default">Kata @index: @file</button>
                                    }
                                }
                            }
                        }
                    </td>
                }
                                   
            }
        </tr>
        <tr>
            @{
                if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                {
                    <td>
                        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#laboratory">Laboratory</button>
                    </td>

                    var user = UserManager.GetUserAsync(User).Result;
                    var currentUser = user.FirstName + user.LastName;
                    var labList = new List<Guid>();

                    <td style="font-size: 16px;">
                        <div id="laboratory" class="collapse">
                            <ul style="list-style-type: none;">
                                @for (var index = 1; index <= 7; ++index)
                                {
                                    var value = Guid.NewGuid();
                                    labList.Add(value);

                                    <li><button type="button" class="btn btn-info" data-toggle="collapse" data-target="#@value">Laboratory nr. @index</button></li>
                                }
                            </ul>
                        </div>
                    </td>
                    <td>
                        @{
                            for (var index = 0; index < labList.Count; ++index)
                            {
                                <div id="@labList[index]" class="collapse">
                                        @foreach (var file in Service.GetAllFiles("Laboratory", (index + 1).ToString(), currentUser))
                                        {
                                            using (Html.BeginForm("Download", "Uploads", new {seminarName = "Laboratory", week = (index + 1).ToString(), fileName = @file, teacher = @currentUser }, FormMethod.Post, null, new {}))
                                            {
                                                <button class="btn btn-default">@file</button>
                                            }
                                        }
                                </div>
                            }
                        }
                    </td>
                }
                else
                {
                    var currentUser = UserManager.Users.SingleOrDefault(user => user.Id == UserManager.GetUserId(User));
                    var teachers = new List<string>();
                    var userFound = currentUser.FirstName + "" + currentUser.LastName + "" + currentUser.Group;

                    foreach (var user in UserManager.GetUsersInRoleAsync("Assistant").Result)
                    {
                        teachers.Add(@user.FirstName + @user.LastName);
                    }

                    <td style="font-size: 16px;">Laboratory</td>
                    <td style="font-size: 16px;">
                        @foreach (var teacher in teachers)
                        {
                            for (var index = 1; index <= 7; ++index)
                            {
                                foreach (var file in Service.GetFiles("Laboratory", index.ToString(), userFound, teacher))
                                {
                                    using (Html.BeginForm("Download", "Uploads", new { seminarName = "Laboratory", week = index.ToString(), fileName = @file, teacher = @teacher }, FormMethod.Post, null, new { }))
                                    {
                                        <button class="btn btn-default">Laboratory @index: @file</button>
                                    }
                                }
                            }
                        }
                    </td>
                }
            }
       </tr>
    </tbody>
</table>