CourseManager/Presentation/Controllers/PresencesController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Business.ServicesInterfaces;
using Business.ServicesInterfaces.Models.PresenceViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Presentation.Controllers
{
    [Authorize]
    public class PresencesController : Controller
    {
        private readonly IPresenceService _service;

        public PresencesController(IPresenceService service)
        {
            _service = service;
        }

        //GET: Presences
        public IActionResult Index()
        {
            foreach(var item in _service.GetAllPresences())
            {
                item.Students = _service.GetUsersByFactionId(item.Id).ToList();
                foreach(var student in item.Students)
                {
                    student.Attendance = _service.GetAttendanceByUserId(student.Id).OrderBy(att => att.StartDate).ToList();
                }
            }

            return View(_service.GetAllPresences());
        }

        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult CreateFaction()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult CreateFaction([Bind("Name")] PresenceCreateModel presenceCreateModel)
        {
            if (!ModelState.IsValid) {
                return View(presenceCreateModel);
            }

            _service.CreateFaction(presenceCreateModel);
            
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult StartPresence(Guid factionId, int labValue)
        {
            _service.StartPresenceBasedOnValue(factionId, labValue);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult StopPresence(Guid factionId)
        {
            _service.StopPresence(factionId);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult MarkAsPresent()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MarkAsPresent(string userId, [Bind("Presence")] UserStatusCreateModel userCreateModel)
        {
            if (!ModelState.IsValid)
            {
                return View(userCreateModel);
            }

            var check = _service.GetAllAttendances().Where(att => att.UserId == userId).ToList().Count;

            if (check != 0)
            {
                try
                {
                    _service.ModifyPresence(userId, userCreateModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.UserStatusExists(_service.GetUserById(userId).Id))
                    {
                        return NotFound();
                    }

                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult UpdatePresence(Guid attendanceId)
        {
            TempData["value"] = attendanceId;

            if (attendanceId.Equals(null))
            {
                return NotFound();
            }

            var userActivity = _service.GetAllAttendances().SingleOrDefault(user => user.Id == attendanceId);
            if (userActivity == null)
            {
                return NotFound();
            }

            var userEditActivity = new UserStatusEditModel(
                userActivity.Presence,
                userActivity.LaboratoryMark,
                userActivity.KataMark
            );

            return View(userEditActivity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult UpdatePresence(Guid attendanceId, [Bind("LaboratoryMark, KataMark, Presence")] UserStatusEditModel userStatusEditModel)
        {
            var userToBeEdited = _service.GetAllAttendances().SingleOrDefault(user => user.Id == attendanceId);

            if (userToBeEdited == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(userStatusEditModel);
            }

            userToBeEdited.Presence = userStatusEditModel.Presence;
            userToBeEdited.LaboratoryMark = userStatusEditModel.LaboratoryMark;
            userToBeEdited.KataMark = userStatusEditModel.KataMark;

            try
            {
                _service.EditAttendance(userToBeEdited);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_service.UserStatusExists(_service.GetUserById(userToBeEdited.UserId).Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: UserAccounts/Delete/5
        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null) {
                return NotFound();
            }

            var presence = _service.GetPresenceById(id.Value);

            if (presence == null)
            {
                return NotFound();
            }

            var userStatus = _service.GetAllUsers().Where(user => user.FactionId == id.Value);
            
            if(userStatus.Equals(null))
            {
                return NotFound();
            }

            return View(presence);
        }
        
        // POST: UserAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner, Assistant")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _service.DeleteData(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

CourseManager/Presentation/Views/Presences/Attendance.cshtml
@using Presentation.Models.PresenceViewModels
@model UserStatusCreateModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Attendance";
}

<h2>Create</h2>

<h4>Faction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Attendance", "Presences", new { userId = UserManager.GetUserId(User)}, FormMethod.Post, null, new { }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Presence" class="control-label"></label>
                <input asp-for="Presence" class="form-control"/>
                <span asp-validation-for="Presence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseManager/Presentation/Views/Presences/CreateFaction.cshtml
@model Business.ServicesInterfaces.Models.PresenceViewModels.PresenceCreateModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Create Faction";
}

<h2>Create Presence</h2>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form multiple="multiple" runat="server" asp-action="CreateFaction">
            <div class="form-group">
                <label asp-for="Name" class="control-label">Groups</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
</div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseManager/Presentation/Views/Presences/CreateLaboratory.cshtml
@using Presentation.Models.PresenceViewModels
@model Presentation.Models.PresenceViewModels.PresenceCreateModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Create Laboratory";
}

<h2>Create Presence</h2>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form multiple="multiple" runat="server" asp-action="CreateLaboratory">
            <div class="form-group">
                <label asp-for="Name" class="control-label">Groups</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseManager/Presentation/Views/Presences/CreatePresence.cshtml
@model Presentation.Models.PresenceViewModels.PresenceCreateModel

@{
    ViewData["Title"] = "Create Presence";
}

<h2>Create Presence</h2>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePresence">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Laboratory" class="control-label"></label>
                <input asp-for="Laboratory" class="form-control" />
                <span asp-validation-for="Laboratory" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Present" class="control-label"></label>
                <input asp-for="Present" class="form-control" />
                <span asp-validation-for="Present" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseManager/Presentation/Views/Presences/Delete.cshtml
@model Presence
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Presence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        
        @*<dt>
            @Html.DisplayNameFor(model => model.Students)
        </dt>
        <dd>
            @foreach (var student in Model.Students)
            {
                var currentUser = UserManager.Users.SingleOrDefault(user => user.Id == student.Id);
                var displayName = currentUser.FirstName + currentUser.LastName;
                    
                @Html.DisplayFor(modelItem => displayName)
                    
                <br />
            }
        </dd>*@
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a class="btn btn-default" asp-action="Index">Back to List</a>
    </form>
</div>

CourseManager/Presentation/Views/Presences/Index.cshtml
@using Business.ServicesInterfaces
@model IEnumerable<Presence>
@inject IPresenceService Service
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Index";
}

<h2>Presences</h2>

@if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
{
    <p>
        <a class="btn btn-default" asp-action="CreateFaction">Create Faction</a>
    </p>
}
else
{
    <p>
        <a class="btn btn-default" asp-action="MarkAsPresent">Mark as present</a>
    </p>
}

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Informations
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        var value = Guid.NewGuid();
        <tr>
            <td>
                <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#@value">@item.Name</button>
            </td>

            <td>
                <div id="@value" class="collapse">
                    <table class="table">
                        <tr>
                            @{
                                var space = "---------";
                                var numberOfStudents = Service.GetUsersByFactionId(item.Id);
                                var userList = Service.GetUsersByFactionId(item.Id).Select(index => index.Id).ToList();

                                <th>
                                    @Html.DisplayFor(modelItem => space)
                                </th>

                                for (var index = 1; index <= 7; ++index)
                                {
                                    var numberOfLaboratories = 0;

                                    foreach (var givenUser in userList)
                                    {
                                        numberOfLaboratories += Service.GetAllAttendances().Count(att => att.UserId == givenUser);
                                    }
                                    
                                    var pastLaboratories = numberOfLaboratories / numberOfStudents.Count;
                                    var pass = false;

                                    <th>
                                        @{
                                            var change = numberOfStudents.FirstOrDefault().CanMarkAsPresent;

                                            if (index - pastLaboratories < 0)
                                            {
                                                <button class="btn btn-default">Finished</button>
                                            }
                                            else if (index - pastLaboratories == 0)
                                            {
                                                if (change)
                                                {
                                                    if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                                                    {
                                                        using (Html.BeginForm("StopPresence", "Presences", new {factionId = item.Id}, FormMethod.Post, null, new {}))
                                                        {
                                                            <button class="btn btn-default">Stop presence</button>
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    <button class="btn btn-default">Finished</button>
                                                }
                                            }
                                            else
                                            {
                                                if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                                                {
                                                    if (change && pass)
                                                    {
                                                        using (Html.BeginForm("StopPresence", "Presences", new {factionId = item.Id}, FormMethod.Post, null, new {}))
                                                        {
                                                            <button class="btn btn-default">Stop presence</button>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        using (Html.BeginForm("StartPresence", "Presences", new {factionId = item.Id, labValue = index}, FormMethod.Post, null, new {}))
                                                        {
                                                            <button class="btn btn-default">Start presence</button>
                                                        }

                                                        pass = true;
                                                    }
                                                }
                                            }
                                        }

                                        Week @Html.DisplayFor(modelItem => index)
                                    </th>
                                        
                                }

                            }
                        </tr>
                        <tr>
                            @{
                                var presence = "P|";
                                var lab = "L|";
                                var kata = "K|";
                                var actions = "Actions";
                                var stud = "Student";
                                <th>
                                    @Html.DisplayFor(modelItem => stud)
                                </th>

                                for (var index = 1; index <= 7; ++index)
                                {
                                    <th>
                                        @Html.DisplayFor(modelItem => presence)
                                        @Html.DisplayFor(modelItem => lab)
                                        @Html.DisplayFor(modelItem => kata)

                                        @if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                                        {
                                            @Html.DisplayFor(modelItem => actions)
                                        }
                                    </th>
                                }
                            }
                        </tr>
                        @foreach (var student in item.Students)
                        {
                            <tr>
                                @{
                                    var currentUser = UserManager.Users.SingleOrDefault(user => user.Id == student.Id);
                                    var displayName = currentUser.FirstName + currentUser.LastName;
                                    <th>
                                        @Html.DisplayFor(modelItem => displayName)
                                    </th>

                                    foreach (var activ in student.Attendance)
                                    {
                                        <td>
                                            @Html.DisplayFor(modelItem => activ.Presence)
                                            @Html.DisplayFor(modelItem => activ.LaboratoryMark)
                                            @Html.DisplayFor(modelItem => activ.KataMark)

                                            @if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                                            {
                                                @Html.ActionLink("Edit", "UpdatePresence", "Presences", new { attendanceId = activ.Id }, null)
                                            }
                                        </td>
                                    }
                                }
                            </tr>
                        }
                    </table>
                </div>
            </td>

            <td>
                @if (User.IsInRole("Assistant") || User.IsInRole("Owner"))
                {
                    <a class="btn btn-default" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
    }
    </tbody>
</table>

CourseManager/Presentation/Views/Presences/MarkAsPresent.cshtml
@model Business.ServicesInterfaces.Models.PresenceViewModels.UserStatusCreateModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "MarkAsPresent";
}

<h2>Create</h2>

<h4>Faction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("MarkAsPresent", "Presences", new { userId = UserManager.GetUserId(User)}, FormMethod.Post, null, new { }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Presence" class="control-label"></label>
                <input asp-for="Presence" class="form-control"/>
                <span asp-validation-for="Presence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        }
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseManager/Presentation/Views/Presences/UpdatePresence.cshtml
@model Business.ServicesInterfaces.Models.PresenceViewModels.UserStatusEditModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Edit Presence";
}

<h2>Edit</h2>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("UpdatePresence", "Presences", new { attendanceId = @TempData["value"] }, FormMethod.Post, null, new { }))
        {
            <div class="form-group">
                <label asp-for="Presence" class="control-label"></label>
                <input asp-for="Presence" class="form-control" />
                <span asp-validation-for="Presence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KataMark" class="control-label"></label>
                <input asp-for="KataMark" class="form-control" />
                <span asp-validation-for="KataMark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LaboratoryMark" class="control-label"></label>
                <input asp-for="LaboratoryMark" class="form-control" />
                <span asp-validation-for="LaboratoryMark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        }
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}